2021-07-30 16:07:38,574 INFO    MainThread:68025 [wandb_setup.py:_flush():69] setting env: {}
2021-07-30 16:07:38,575 INFO    MainThread:68025 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-30 16:07:38,575 INFO    MainThread:68025 [wandb_init.py:_log_setup():337] Logging user logs to /Users/mozharovsky/GitHub/git-t5/git_t5/outputs/2021-07-30/16-00-11/wandb/run-20210730_160738-201mvdh9/logs/debug.log
2021-07-30 16:07:38,576 INFO    MainThread:68025 [wandb_init.py:_log_setup():338] Logging internal logs to /Users/mozharovsky/GitHub/git-t5/git_t5/outputs/2021-07-30/16-00-11/wandb/run-20210730_160738-201mvdh9/logs/debug-internal.log
2021-07-30 16:07:38,576 INFO    MainThread:68025 [wandb_init.py:init():370] calling init triggers
2021-07-30 16:07:38,576 INFO    MainThread:68025 [wandb_init.py:init():377] wandb.init called with sweep_config: {}
config: {}
2021-07-30 16:07:38,576 INFO    MainThread:68025 [wandb_init.py:init():419] starting backend
2021-07-30 16:07:38,576 INFO    MainThread:68025 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-07-30 16:07:38,592 INFO    MainThread:68025 [backend.py:ensure_launched():135] starting backend process...
2021-07-30 16:07:38,600 INFO    MainThread:68025 [backend.py:ensure_launched():140] started backend process with pid: 72026
2021-07-30 16:07:38,603 INFO    MainThread:68025 [wandb_init.py:init():424] backend started and connected
2021-07-30 16:07:38,605 INFO    MainThread:68025 [wandb_init.py:init():472] updated telemetry
2021-07-30 16:07:38,606 INFO    MainThread:68025 [wandb_init.py:init():491] communicating current version
2021-07-30 16:07:43,610 INFO    MainThread:68025 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-07-30 16:08:13,616 INFO    MainThread:68025 [interface.py:_communicate_run():656] couldn't get run from backend
2021-07-30 16:08:13,618 ERROR   MainThread:68025 [wandb_init.py:init():508] backend process timed out
2021-07-30 16:08:13,618 ERROR   MainThread:68025 [wandb_init.py:init():517] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-07-30 16:08:13,632 ERROR   MainThread:68025 [wandb_init.py:init():787] error
Traceback (most recent call last):
  File "/Users/mozharovsky/GitHub/git-t5/.venv/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 761, in init
    run = wi.init()
  File "/Users/mozharovsky/GitHub/git-t5/.venv/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 520, in init
    backend.cleanup()
  File "/Users/mozharovsky/GitHub/git-t5/.venv/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 167, in cleanup
    self.interface.join()
  File "/Users/mozharovsky/GitHub/git-t5/.venv/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 835, in join
    _ = self._communicate(record)
  File "/Users/mozharovsky/GitHub/git-t5/.venv/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 544, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/mozharovsky/GitHub/git-t5/.venv/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 549, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
